var properties = 
 { "default.language" : "en",
  "use.stemming" : "false",
  "webhelp.enable.scroll.to.search.term" : "no",
  "webhelp.enable.search.autocomplete" : "yes",
  "webhelp.enable.search.kuromoji.js" : "true",
  "webhelp.enable.sticky.header" : "yes",
  "webhelp.enable.sticky.publication.toc" : "no",
  "webhelp.enable.sticky.topic.toc" : "no",
  "webhelp.enable.template.js.module.loading" : "no",
  "webhelp.labels.generation.mode" : "keywords-label",
  "webhelp.language" : "fr",
  "webhelp.publication.toc.links" : "chapter",
  "webhelp.publication.toc.tooltip.position" : "right",
  "webhelp.search.default.operator" : "or",
  "webhelp.search.enable.pagination" : "true",
  "webhelp.search.page.numberOfItems" : "10",
  "webhelp.search.ranking" : "true",
  "webhelp.show.expand.collapse.sections" : "no",
  "webhelp.show.full.size.image" : "true",
  "webhelp.show.indexterms.link" : "yes",
  "webhelp.show.main.page.tiles" : "yes",
  "webhelp.show.main.page.toc" : "no",
  "webhelp.show.print.link" : "no",
  "webhelp.top.menu.depth" : "1",
  "webhelp.topic.collapsible.elements.initial.state" : "expanded" };